theme: jekyll-theme-tactile
title: Sqlite Provider in the new Ionic 2 framework.
description: The new look Ionic 2 has the structure of a project re-organized. There are plenty of posts relating to Sqlite Provider but not many dedicated one for this new structure. This project is just a simple tutorial on this subject.
