theme: jekyll-theme-tactile
title: Sqlite Provider in the new Ionic 2 framework.
description: The new look of Ionic 2 has the project structure re-organized. There are plenty of posts showing how to integrate Sqlite Provider but not updating for this new structure. This project is just a simple tutorial on this subject.
